language: node_js
before_install:
  - npm install -g grunt grunt-cli
before_script:
  - grunt coffee
node_js:
  - "0.10"
script:
  - grunt travis
after_script:
  - CODECLIMATE_REPO_TOKEN=33e8f82a9ab973a223787487206a03312d98a161f07105793c293307c943b16d cat coverage/reports/lcov.info | codeclimate

notifications:
  slack:
    masuilab:p4zvcihWTFLz1KwJXYGwJgeZ

